package com.chrissmith.blocknine.leaderboard

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.tasks.await

/** One row on a board. */
data class Entry(
    val uid: String,
    val name: String,
    val score: Int,
)

/** Who is signed in, if anyone. */
data class Player(val uid: String, val name: String, val photoUrl: String?)

/**
 * Google sign-in plus the leaderboard documents.
 *
 * Every player owns exactly one document at `players/{uid}` holding their all-time best
 * alongside a best-for-today and best-for-this-month, each paired with the bucket key it
 * belongs to. Keeping all three on one document means a score submission is a single write,
 * and each board is one indexed query — the dated boards filter on their key first so last
 * month's numbers can't leak into this month's ranking.
 */
class LeaderboardRepository(private val context: Context) {

    /**
     * False until a Firebase project is wired up. FirebaseApp auto-initialises from resources
     * generated by the google-services plugin, so with no google-services.json there is simply
     * no default app — which is the signal that the backend isn't configured.
     */
    val configured: Boolean by lazy { FirebaseApp.getApps(context).isNotEmpty() }

    private val auth: FirebaseAuth by lazy { FirebaseAuth.getInstance() }
    private val db: FirebaseFirestore by lazy { FirebaseFirestore.getInstance() }
    private val players get() = db.collection(COLLECTION)

    fun currentPlayer(): Player? = if (!configured) null else auth.currentUser?.toPlayer()

    private fun FirebaseUser.toPlayer() = Player(
        uid = uid,
        name = displayName?.takeIf { it.isNotBlank() } ?: "Player",
        photoUrl = photoUrl?.toString(),
    )

    /**
     * The web OAuth client id the google-services plugin writes out once Google sign-in is
     * enabled on the project. Looked up by name rather than through `R.string` so the app
     * still compiles when the resource doesn't exist.
     */
    private fun webClientId(): String? {
        val id = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        return if (id == 0) null else context.getString(id)
    }

    /** Runs the Google sign-in sheet. [activityContext] must be an Activity. */
    suspend fun signIn(activityContext: Context): Player {
        check(configured) { "Firebase is not configured" }
        val clientId = webClientId()
            ?: error("Google sign-in is not enabled on the Firebase project")

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(GetSignInWithGoogleOption.Builder(clientId).build())
            .build()

        val response = CredentialManager.create(context).getCredential(activityContext, request)
        val googleIdToken = GoogleIdTokenCredential.createFrom(response.credential.data).idToken
        val result = auth.signInWithCredential(GoogleAuthProvider.getCredential(googleIdToken, null)).await()

        val user = result.user ?: error("Signed in but Firebase returned no user")
        // No profile document is written here on purpose: the rules require a complete row
        // (name plus all three scores), and a player with no finished game has nothing to
        // rank. submit() writes the name alongside the first score.
        return user.toPlayer()
    }

    fun signOut() {
        if (configured) auth.signOut()
    }

    /**
     * Records [score] against the signed-in player, raising each of the three bests only if
     * this game beat it. Run in a transaction because the day and month bests need the stored
     * bucket key to decide between "beat it" and "new period, start again".
     */
    suspend fun submit(score: Int) {
        if (!configured || score <= 0) return
        val player = currentPlayer() ?: return

        val today = Periods.dayKey()
        val thisMonth = Periods.monthKey()
        val doc = players.document(player.uid)

        db.runTransaction { txn ->
            val snapshot = txn.get(doc)
            val storedDay = snapshot.getString(FIELD_DAY_KEY)
            val storedMonth = snapshot.getString(FIELD_MONTH_KEY)

            // A stored best only counts if it belongs to the period being scored.
            val dayBest = if (storedDay == today) snapshot.getLong(FIELD_DAY_BEST) ?: 0L else 0L
            val monthBest = if (storedMonth == thisMonth) snapshot.getLong(FIELD_MONTH_BEST) ?: 0L else 0L
            val allBest = snapshot.getLong(FIELD_BEST) ?: 0L

            txn.set(
                doc,
                mapOf(
                    "name" to player.name,
                    FIELD_BEST to maxOf(allBest, score.toLong()),
                    FIELD_DAY_KEY to today,
                    FIELD_DAY_BEST to maxOf(dayBest, score.toLong()),
                    FIELD_MONTH_KEY to thisMonth,
                    FIELD_MONTH_BEST to maxOf(monthBest, score.toLong()),
                    "updatedAt" to FieldValue.serverTimestamp(),
                ),
                com.google.firebase.firestore.SetOptions.merge(),
            )
        }.await()
    }

    /** Top [limit] players on [period], best first. */
    suspend fun top(period: Period, limit: Long = TOP_N): List<Entry> {
        if (!configured) return emptyList()

        val scoreField = when (period) {
            Period.DAY -> FIELD_DAY_BEST
            Period.MONTH -> FIELD_MONTH_BEST
            Period.ALL -> FIELD_BEST
        }
        val query: Query = when (period) {
            Period.DAY -> players.whereEqualTo(FIELD_DAY_KEY, Periods.dayKey())
            Period.MONTH -> players.whereEqualTo(FIELD_MONTH_KEY, Periods.monthKey())
            Period.ALL -> players
        }

        return query
            .orderBy(scoreField, Query.Direction.DESCENDING)
            .limit(limit)
            .get()
            .await()
            .documents
            .mapNotNull { snapshot ->
                val score = snapshot.getLong(scoreField)?.toInt() ?: return@mapNotNull null
                if (score <= 0) return@mapNotNull null
                Entry(
                    uid = snapshot.id,
                    name = snapshot.getString("name")?.takeIf { it.isNotBlank() } ?: "Player",
                    score = score,
                )
            }
    }

    private companion object {
        const val COLLECTION = "players"
        const val TOP_N = 25L
        const val FIELD_BEST = "best"
        const val FIELD_DAY_KEY = "dayKey"
        const val FIELD_DAY_BEST = "dayBest"
        const val FIELD_MONTH_KEY = "monthKey"
        const val FIELD_MONTH_BEST = "monthBest"
    }
}
